### PR TITLE
Revisit our config for 'Naming' Cops

### PR DESCRIPTION
**Pull request by benthorner**
This has the effect of turning on two cops:

- Naming/AsciiIdentifiers
- Naming/FileName

Please see the commits for more details. Trying to enable Naming/PredicateName
uncovered quite a few issues, so I'm going to leave that one for now.

### CODE REVIEW

**Comment by benthorner** [comment]
Update: turning on `Naming/FileName` isn't so great for Smart Answers, which deliberately uses a lot of hyphens in its filenames. That does seem like a special case, and we can always disable this cop for the offending directories in that repo (or remove the hyphen requirement).

**Comment by AlanGabbianelli** [comment]
Can we enable `Naming/AccessorMethodName` by default and just disable it for the specific cases you mentioned?

**Comment by benthorner** [comment]
@AlanGabbianelli thanks for taking a look 😃. In your comment, are you meaning to refer to `Naming/FileName`? I haven't mentioned `Naming/AccessorMethodName` in this PR, but it's the same problem as `Naming/PredicateName` - there are quite a few (as in lots!) of issues with it, so I'd like to tackle enabling them/that in a single version upgrade.

**Comment by AlanGabbianelli** [comment]
Hey @benthorner, no, I mean `Naming/AccessorMethodName`. In https://github.com/alphagov/rubocop-govuk/commit/c927eab9dcc5db30fa7f6e66989e919387323994 you added an explanation for it as a comment and left the cop disabled.

Instead of that explanation, can we enable this cop by default and only disable it manually for the specific cases you mentioned in the comment such as `def set_political_and_government(edition)`? In a later version bump would be fine too if they are too many to change in this PR.

**Comment by benthorner** [comment]
@AlanGabbianelli oh, I see, sorry. Personally I don't think it's a particularly valuable Cop, and we shouldn't really enable it if our only plan is to do `# rubocop:disable` in lots of places, which creates more clutter. My thinking is that the Cop itself is buggy: it should check the method signature to see if what it's asking for is actually appropriate. And even if it's not, using `name=` vs `set_name` doesn't actually make much difference to me.

I also had a quick look around our apps: doesn't look like we're using the `name=` style anywhere; in general, we just use `attr_writer` or `attr_accessor` to create simple `name=` methods.

Still content to revisit, though - I just don't see it as a quick win now, and there is at least some argument for keeping it as it is. We also argue against that argument in the future 😉.

**Pull request merged**
