### PR TITLE
Reorganise cops by 'department'

### PR DESCRIPTION
**Pull request by benthorner**
Previously it was unclear which file to find a given piece of config in, or
where to put some new config. This reorganises all the config by the
'department' of the cop: 'Style', 'Lint', etc. This will activate two cops:

  - 'Layout/EmptyLines' - the unjustified 'Enabled: false' won
    previously. Should be uncontentious - who wants empty lines?

  - Layout/SpaceBeforeFirstArg - the unjusitifed 'Enabled: false' won
    previosuly. Should be fine - applies to code like 'something"hello"'

Please see the commits for more details.

### CODE REVIEW

**Comment by sihugh** [comment]
There's another duplicate `Layout/SpaceBeforeFirstArg` configuration:

> config/layout.yml:216: `Layout/SpaceBeforeFirstArg` is concealed by line 301

**Comment by issyl0** [comment]
Do we have to :scream: go and edit every app's `.rubocop.yml` now?

**Comment by benthorner** [comment]
@sihugh oops! Thanks for spotting - I had an uncommitted change.

**Comment by benthorner** [comment]
@issyl0 I don't think so. Although the two dodgy cops may cause a few issues, we should be able to auto-correct them easily. Is there something else you're concerned about?

**Comment by issyl0** [comment]
Ah, I saw https://github.com/alphagov/rubocop-govuk/pull/44/files#diff-e93280b3b31a6438c533a5f3232340d8R22-R29 and thought it was in `.rubocop.yml` for this app. But all the apps include `default.yml` as a thing, so it's fine. Sorry, doing too many things at once!

**Pull request merged**
