### PR TITLE
Disable Metrics/BlockLength

### PR DESCRIPTION
**Pull request by benthorner**
This Cop was accruing several overrides across our repos.

### CODE REVIEW

**Comment by kevindew** [comment]
Oh this was actually the thing I was going to open a PR on. 

I would suggest that rather than adding more exceptions to this we disable this rule altogether. I think we've already disabled every other rule that is length based so this one feels inconsistent with our other approach to length based rules.

**Comment by benthorner** [comment]
@kevindew absolutely. I just realised I haven't actually disabled it! My comment is all about disabling it, though 😝

**Comment by kevindew** [comment]
> @kevindew absolutely. I just realised I haven't actually disabled it! My comment is all about disabling it, though 😝

Haha guess who (me) just read the code and not the comment.

**Comment by benthorner** [comment]
@kevindew https://github.com/alphagov/rubocop-govuk/pull/68

**Pull request merged**
